### ISSUE TITLE
afterEvaluate for Task Dependencies

### ISSUE THREAD

**Issue by RobertFischer** [bmuschko/gradle-gae-plugin#10]
I'm a huge fan of the Gradle GAE plugin. Thank you very much for doing this work. There is, however, one issue that I bumped into while working in multiproject builds.

In my multiproject builds, only some apps are GAE. I want to have an "opt-in" system, so that I add to my build.gradle "isGAE = true" and life is good. Unfortunately, you use "afterEvaluate" for your downloadSdk logic in configureGaeSdk, so that kinda messes up the evaluation order.

Instead of doing an "afterEvaluate" hook in configureGaeSdk, can we accomplish the same thing with a task dependencies hook?

The code currently looks like this:

``` groovy
        project.afterEvaluate {
            if(gaePluginConvention.downloadSdk) {
                project.tasks.findAll { task -> task.name.startsWith('gae') && task.name != GAE_DOWNLOAD_SDK }.each { gaeTask ->
                    gaeTask.dependsOn project.tasks.getByName(GAE_DOWNLOAD_SDK)
                }
            }
        }
```

I'd propose changing it to something like this:

``` groovy
project.tasks.all { Task task ->
  if(task.name.startsWith('gae') && task.name != GAE_DOWNLOAD_SDK) {
    task.dependsOn {
        if(gaePluginConvention.downloadSdk) {
            return task.project.tasks.getByName(GAE_DOWNLOAD_SDK)
        } else {
            return null
        }
    }
  }
}
```

**Comment by bmuschko** [comment]
Thanks! Makes sense. I am kind of swamped with work right now but I will try to integrate it as soon as possible.

**Comment by RobertFischer** [comment]
I can fork it and submit a patch request if you'd like.

~~ Robert.

On Mon, Jan 23, 2012 at 10:12 PM, Benjamin Muschko
reply@reply.github.com
wrote:

**Comment by bmuschko** [comment]
It seems like this issue is the more pressing issue for you. [Issue 11](https://github.com/bmuschko/gradle-gae-plugin/issues/11) appears to be more like a nice to have but will certainly involve more work and testing. Basically you already provided the patch. I might find some time tonight to put it in but sending a pull request is always welcome.

**Comment by RobertFischer** [comment]
Thanks! I appreciate the thoughtfulness, and long live the GAE plugin! :)

~~ Robert.

On Tue, Jan 24, 2012 at 7:30 AM, Benjamin Muschko
reply@reply.github.com
wrote:

**Comment by bmuschko** [comment]
Word! Here you go.
