### ISSUE TITLE
Only one SDK for multiproject builds

### ISSUE THREAD

**Issue by RobertFischer** [bmuschko/gradle-gae-plugin#11]
Can you move the downloaded Google App Engine SDK directory to rootDir/build, and hook the downloadSdk task onto the rootProject instead of into the plugin-installed project? That way, multiple builds only need to download and expand the SDK once.

(You will want to version that SDK path in case there are multiproject builds that are built against multiple GAE SDK versions for some crazy reason.)

**Comment by musketyr** [comment]
in fact, it will make more reason to place the sdk somewhere in user dir in `.gradle`, `.gae` or some other reasonable sheard place. having 100MB+ SDK in each project is quite space consuming.

**Comment by RobertFischer** [comment]
If we go with that approach, we'll want to make sure to version the
path, since different projects might use different SDKs.

~~ Robert.

On Thu, May 31, 2012 at 9:18 AM, musketyr
reply@reply.github.com
wrote:

**Comment by musketyr** [comment]
I can't see any problem. You already can have different SDK in single project if you upgrade the App Engine version. The shared folder should be similar to `build\expoloded-gae-sdk` content.

This means it should have following structure

```
.app-engine-sdks
  |
  + appengine-java-sdk-1.4.5
  |
  .
  .
  .
  |
  + appengine-java-sdk-1.6.6
```

**Comment by RobertFischer** [comment]
Yeah, I don't see it as a problem, either. I just wanted to make sure
we were thinking about that.

~~ Robert.

On Thu, May 31, 2012 at 9:39 AM, musketyr
reply@reply.github.com
wrote:

**Comment by bmuschko** [comment]
I like the idea of putting it into a common directory e.g. `~/.app-engine-sdks`. IMHO we don't need a versioning-strategy as the SDK version number already indicates that.

**Comment by bmuschko** [comment]
All downloaded App Engine SDKs will be stored in `~/.gradle/gae-sdk`.
