### ISSUE TITLE
support backend commands

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#13]
following commands for managing backends are not implemented yet

http://code.google.com/intl/cs/appengine/docs/java/backends/overview.html#Commands

**Comment by musketyr** [comment]
there might be also some task like `gaeUploadAll` which will simply upload to the frontend and all backends because this is the most common use case.

**Comment by bmuschko** [comment]
I added all `backends` tasks to the plugin in a [separate branch](https://github.com/bmuschko/gradle-gae-plugin/tree/backends). Can you do me a favor and try it out before I merge it into master and release it?

**Comment by musketyr** [comment]
ok. I'll try it and let you know

**Comment by musketyr** [comment]
works like a charm. good work, thx!
