### ISSUE TITLE
Ability resolve dependencies without copy when gaeRun on source director

### ISSUE THREAD

**Issue by codeconsole** [bmuschko/gradle-gae-plugin#15]
It would be nice to be able to do something like this:

```
gae {
    runtimeClasspath = compileGroovy.classpath
    warDir = file('src/main/webapp')
}
```

Such that all project dependencies could be resolved without having to be copied to the src/main/webapp/lib or src/main/webapp/classes folder.

This way you can view changes on the fly without having to restart the server and you don't have to pollute your source folder with binary files.

**Comment by bmuschko** [comment]
I think we are restricted here by what [options are supported by Google](https://developers.google.com/appengine/docs/java/tools/devserver) for the local development server. It doesn't look to me as if there would be an option to explicitly set a classpath. You can only define the WAR location. Maybe you have more insight into this. The only way I could potentially think of to make this work is to use a context ClassLoader for the current thread. The development server might not respect this though.

**Comment by codeconsole** [comment]
lol. It looks like you already asked this question:

https://groups.google.com/forum/?fromgroups#!topic/google-appengine-java/jl7FxszABIs

**Comment by codeconsole** [comment]
Hmm, so that sucks.  Is it possible to run a background thread that syncs the source webapp folder with the build folder every 10 seconds?

**Comment by codeconsole** [comment]
_hopefully_ they will just consider this:

http://code.google.com/p/googleappengine/issues/detail?id=7346

**Comment by bmuschko** [comment]
Haha, I totally forgot that I had asked that question on the mailing list before. Thanks for creating the issue. Certainly it would be possible to write a background thread that syncs directories. I don't think I will get to it this weekend but I am positive that I am going to find some time during the upcoming weeks. I know this sounds really vague but if you want to work on it feel free to send me a pull request.

**Comment by pixoto** [comment]
Looks like this can be accomplished by JRebel as well.  This is what the mvn gae plugin uses. Maybe add JRebel support? 

http://zeroturnaround.com/blog/jrebel-gradle-plugin-beta/
http://www.kindleit.net/maven_gae_plugin/faq.html

**Comment by bmuschko** [comment]
JRebel doesn't require an actual code change. You could already try to make it work with the GAE plugin. I wrote a paragraph on [using JRebel with the Gradle Tomcat plugin](https://github.com/bmuschko/gradle-tomcat-plugin#faq) a while ago. That should get you started.

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
