### ISSUE TITLE
consider `warDir` option as deprecated

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#17]
because the app should always run from built exploded war

**Comment by bmuschko** [comment]
I am going to keep it in case somebody wants to work on a project structure that is not going to be the exploded WAR directory. As the exploded WAR directory is the default value it won't require additional configuration.

**Comment by musketyr** [comment]
you were right. I still need to define war dir if I want to used rapid development features in Gaelyk
