### ISSUE TITLE
gae backend tasks should use exploded war folder

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#18]
instead of web app source directory

**Comment by bmuschko** [comment]
Do you consider this to be a bug? I guess from the documentation I couldn't quite figure out whether `<dir>` is the web application directory or the WAR directory.

**Comment by musketyr** [comment]
well, the problem is that I to point to the same dir as gaeUpload does. if it points to source dir it just uploads the web app  without classes/libs causing ClassNotFoundException

**Comment by bmuschko** [comment]
I put a fix in place on this [branch](https://github.com/bmuschko/gradle-gae-plugin/tree/backends-fix) for the backends update tasks. These tasks now depend on `gaeUpload` and will use the exploded WAR directory in the command (see [commit](https://github.com/bmuschko/gradle-gae-plugin/commit/5343c2880b3606d428b157b7c8e8b940ace34a7d)). Can you give it a try and let me know if that fixes your problem? I was also wondering if the other backends tasks work as expected?

**Comment by musketyr** [comment]
cool thanks. I'll check it probably this weekend or next week. I've got some deadlines this week.

**Comment by musketyr** [comment]
works excellent. could you also add gaeUploadAll task which will depend on gaeUpload and gaeUploadAllBackends. these two are often used together. 

would you mind if I publish gae gradle plugin and gaelyk gradle plugin on maven central under org.gaelyk group id?

**Comment by bmuschko** [comment]
Sure thing. Will add the task.

I was always hesitant to upload the Gradle plugins to Maven as I was waiting for Gradleware to provide a custom plugin repository. But yeah...I can do that for sure.

**Comment by musketyr** [comment]
Cool.

As Gradle Roadmap says 'Discussions are happening and work will start not long after the release of 1.0' about plugin repository we could wait a year or so until it's done.

**Comment by musketyr** [comment]
so, should I publish it using 'org.gaelyk' or will you do it under your group id?

**Comment by bmuschko** [comment]
I will need to add the task and configuration for uploading it to Maven Central first. I am going to publish it under a different group ID than `org.gaelyk` as it actually is not Gaelyk-specific. Any Java project using Google App Engine can use it.

**Comment by bmuschko** [comment]
I added the task `gaeUploadAll` as well. Give it a spin and let me know. If it works as expected I will release a new plugin version and upload it to Maven Central.

**Comment by musketyr** [comment]
thanks, it works well.

**Comment by bmuschko** [comment]
I released a new version of the plugin and created a separate [issue](https://github.com/bmuschko/gradle-gae-plugin/issues/21) for uploading it to Maven Central.
