### ISSUE TITLE
add ability to override application id and version

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#19]
in gradle file and in command line for e.g. testing purposes

see [-A and -V switches](https://developers.google.com/appengine/docs/java/tools/uploadinganapp#Command_Line_Arguments) for appcfg utility

**Comment by bmuschko** [comment]
As far as I can see these two flags are only used for the task `download_app`. This will be implemented with [Issue #20](https://github.com/bmuschko/gradle-gae-plugin/issues/20).

**Comment by musketyr** [comment]
hmm... what a pity. but we can still provide the feature. after `gaeExplodeWar` update `application` and `version` tags in `appengine-web.xml` file

**Comment by bmuschko** [comment]
I don't think I quite understand the use case for this. If you wanted to change these values for testing purposes why don't you just change `appengine-web.xml` directly?

**Comment by musketyr** [comment]
the typical use case are functional tests in automatic build. I would like to deploy the app automatically into some test application id or version and then run e.g. Geb specs against it. if everything's ok only than upload the app with the original id.
