### ISSUE TITLE
Upload plugin to Maven Central

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-gae-plugin#21]
The plugin should be accessible on Maven Central. For that reason prepare the Gradle build file to sign and upload the JAR/POM.

**Comment by bmuschko** [comment]
I am currently waiting on access for publishing to [Maven Central](https://issues.sonatype.org/browse/OSSRH-3605).

**Comment by musketyr** [comment]
cool. not sure you'll be able to commit with `org.gradle.api.plugins` group id.

**Comment by bmuschko** [comment]
I actually already pushed to that group ID but it's not syncing on Maven Central. Any ideas based on my [ticket description](https://issues.sonatype.org/browse/OSSRH-3628)?

**Comment by musketyr** [comment]
have you closed and released it from https://oss.sonatype.org/index.html#stagingRepositories as well?

**Comment by bmuschko** [comment]
Doh, forgot to promote the release. It should show up soon in Maven Central. Will close the ticket when it's available.

**Comment by musketyr** [comment]
it sometimes happen :-) cool. do you release gradle-gaelyk-plugin as well?

**Comment by bmuschko** [comment]
Yeah, I think it would be a good idea in the future. Not for this release though. I was actually thinking about moving it under the Gaelyk repository. We can talk about this on the mailing list. Also we'd need to agree on a group ID. I created a [ticket](https://github.com/bmuschko/gradle-gaelyk-plugin/issues/9) for it. Let's have the discussion there.

**Comment by musketyr** [comment]
hmm.. I was hoping 1.2 template will have all the dependencies in maven central :(

I have the rights to upload as 'org.gaelyk' to maven central, so I could do it if you thing it's better

**Comment by bmuschko** [comment]
Promoted to [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22gradle-gae-plugin%22).
