### ISSUE TITLE
gaeRun fails when Java 7u4 used

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#25]
reported by @robfletcher

details here

http://pastebin.com/rP1WAunw
http://pastebin.com/r72ff0gC

**Comment by bmuschko** [comment]
Based on the Google App Engine Java [overview page](https://developers.google.com/appengine/docs/java/overview) only the Java versions 5 and 6 are officially supported. I guess specific Java 7 versions are not fully compatible yet. I raised the [question on Stackoverflow](http://stackoverflow.com/questions/11006281/java-7-support-for-google-app-engine-java) as the GAE Google groups have been [deprecated](https://groups.google.com/forum/?fromgroups#!topic/google-appengine/Z6XN_64cA7w).

**Comment by bmuschko** [comment]
Google says that there are known issues with Java 7. At the moment it's not on the roadmap yet.

**Comment by bmuschko** [comment]
The [announcement for GAE 1.7.3](http://googleappengine.blogspot.com/2012/10/app-engine-173-released.html) states that there's support for JDK 7 in the local development environment. Support for JDK 7 as runtime environment (I guess on their servers) will follow in an upcoming version. Sounds like it's worth a shot.
