### ISSUE TITLE
gaeStop kills gradle VM

### ISSUE THREAD

**Issue by axelfontaine** [bmuschko/gradle-gae-plugin#3]
If I have something like:

task myGaeTask(dependsOn: [gaeExplodeWar, gaeRun, gaeStop, myOtherTask]) {
}

myOtherTask never gets executed as the gradle VM gets killed before

**Comment by bmuschko** [comment]
_Note:_ You don't need to call `gaeExplodeWar` if you set a value for the convention property `warDir`. The task `gaeRun` checks the property and calls `gaeExplodeWar` before running `gaeRun` automatically. See the class [GaePlugin.groovy](https://github.com/bmuschko/gradle-gae-plugin/blob/master/src/main/groovy/org/gradle/api/plugins/gae/GaePlugin.groovy) for more information.
