### ISSUE TITLE
Java 7 Support

### ISSUE THREAD

**Issue by codeconsole** [bmuschko/gradle-gae-plugin#33]
In order to upload a Java 7 application, you need to pass the `--use_java7` flag to update.

```
appcfg.sh --use_java7 update <app_dir>
```

**Comment by bmuschko** [comment]
Is this option documented somewhere? I couldn't find it in the section ["Uploading and Managing a Java App"](https://developers.google.com/appengine/docs/java/tools/uploadinganapp).

**Comment by codeconsole** [comment]
The Documentation is only available for trusted testers.

**Comment by bmuschko** [comment]
OK. Does this flag only apply to the `update` command or can it be used for other `appcfg.sh` commands as well?

**Comment by codeconsole** [comment]
I believe only update.  What other command would you use it with?

**Comment by bmuschko** [comment]
I guess I was thinking along the lines of `update_cron` or `update_indexes`. However, looking at it again my question doesn't really make sense as these commands only update the definitions from XML files.

**Comment by ludoch** [comment]
No real need to fix now . As soon as you have some java7 bytecode in your classes or jar, the tools picks a java7 target. (1.7.5)
