### ISSUE TITLE
JDO3 Support

### ISSUE THREAD

**Issue by devesh** [bmuschko/gradle-gae-plugin#34]
https://developers.google.com/appengine/docs/java/datastore/jdo/overview-dn2#Migrating_to_Version_2.0_of_the_DataNucleus_Plugin describes the changes to enhance classes for JDO 3 in ant. Make corresponding changes for gradle.

**Comment by bmuschko** [comment]
Personally, I am not using JDO but I had a look at the documentation mentioned above. Is it correct that the only change from the tooling aspect is adding the following arguments to the Ant task `enhance_war`?

```
<arg value="-enhancerVersion"/>
<arg value="v2"/>
```

Is there anything else missing from your point of view?

**Comment by bmuschko** [comment]
Do you have any updates on this issue? Any leads would be great so I can implement the feature appropriately. If you could give me the code that made it work for you in Ant is all I need. Feel free to post it in this ticket.

**Comment by devesh** [comment]
Oh, sorry. I decided not to use JDO in my new project and forgot that I was the one who reported this issue. Yes, I think you just have to add those two arguments to the Ant task.

https://github.com/cherrot/GWT-GAE-JDO3-Maven3 looks like a good candidate for testing that your fix works.

**Comment by bmuschko** [comment]
OK, thanks for the input.

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
