### ISSUE TITLE
Add javaAgent option

### ISSUE THREAD

**Issue by marceloverdijk** [bmuschko/gradle-gae-plugin#39]
Please add javaAgent option just like Maven GAE Plugin has:

`<javaAgent>${env.JREBEL_HOME}/jrebel.jar</javaAgent>`

**Comment by bmuschko** [comment]
You can already declare the agent via the `jvmArgs` convention property. Here's an example:

```
gae {
    jvmFlags = ['-javaagent:/Users/Ben/dev/tools/jrebel/jrebel.jar']
}
```

Setting this value provides the following option: 

`--jvm_flag=-javaagent:/Users/Ben/dev/tools/jrebel/jrebel.jar`

The Maven GAE plugin [does exactly the same thing internally](https://github.com/maven-gae-plugin/maven-gae-plugin/blob/master/maven-gae-plugin/src/main/java/net/kindleit/gae/StartGoal.java#L124). I don't see the need to introduce a specific property for setting the Java agent.

**Comment by bmuschko** [comment]
I assume that's a sufficient solution for your use case?

**Comment by marceloverdijk** [comment]
Yes I'm using that already.It should be sufficient. Thx
