### ISSUE TITLE
What is best way to generate rebel.xml?

### ISSUE THREAD

**Issue by marceloverdijk** [bmuschko/gradle-gae-plugin#40]
I'm moving my project from Maven to Gradle and I'm encountering some issue setting up JRebel. In Maven the rebel.xml is generated during the phase process-resources.

In my Gradle file I have enable the rebel plugin and added:

```
rebel {
    alwaysGenerate = "true"
    showGenerated = "true"
}
```

but the rebel.xml is not being generated.
When I do `gradle generateRebel` then the rebel.xml is generated.

Do I have to do something special to generate the rebel.xml during gaeRun or gaeUpdate?

**Comment by bmuschko** [comment]
I wrote a  [FAQ section](https://github.com/bmuschko/gradle-tomcat-plugin#faq) on how to integrate JRebel with a different Gradle plugin. It should give you enough information to set it up for a GAE project. There's nothing special that needs to be done from a GAE plugin standpoint. Please let me know if you have more questions.

If you have specific questions about the JRebel plugin I'd ask the JRebel guys that wrote the plugin.

**Comment by marceloverdijk** [comment]
Hi,
I read the FAQ section before. 
I've set it up similarly only I'm adding the -javaagent setting to the `jvmFlags` option of the plugin.
I've also applied the rebel plugin (tried both 1.0.2-SNAPSHOT and 1.0.3-SNAPSHOT).

I see Rebel kicking in as I see the Rebel license.
But the problem is the rebel.xml is not genereated and hence nothing is reloaded.

Note that I've also the following in my `build.gradle`

```
rebel {
    alwaysGenerate = "true"
    showGenerated = "true"
}
```

It seems when running the `gaeRun` tasks the `rebel.xml` is not generated automatically.
Do I have to do something special to make that happen.
E.g. in Maven I have to set phase process-resources to make this happen.

**Comment by bmuschko** [comment]
I wouldn't think that you'd need to re-generate the `rebel.xml` every time you run the build. The directory path to your classes doesn't really change does it? The question is where does the JRebel plugin hook into to automatically execute the XML generation task. I'd need to have a look at their code. The documentation doesn't really say. It might just be a standalone task that isn't dependent on any other task.

What you could probably do is to let `gaeRun` depend on `generateRebel` by declaring it in your build which automatically executes the task (except if it not UP-TO-DATE):

```
gaeRun.dependsOn generateRebel
```

Another option is to generate the file once and put it in your resources directory e.g. `src/main/resources`. Gradle would automatically copy the file to the classes output directory and use it at runtime. This behavior might be different if you changed the default behavior. Example code to look at would be helpful here.

Hope this helps.

**Comment by bmuschko** [comment]
Did one of the proposed solutions work for you?

**Comment by marceloverdijk** [comment]
I used:

`war.dependsOn generateRebel`

which seems to work now.
The difference with `gaeRun` task you mentioned is that is also picked up by gaeUpdate.

I've also put a question on the JRebel forum to see their opinion: http://zeroturnaround.com/forums/topic/gradle-and-automatic-rebel-xml-generation/

**Comment by marceloverdijk** [comment]
Btw gaeRun should be sufficient. When updating the app to Google's infrastructure rebel.xml is not needed.
