### ISSUE TITLE
Add support for appcfg --enable_jar_classes option during deployment

### ISSUE THREAD

**Issue by adennie** [bmuschko/gradle-gae-plugin#41]
[Feature request] This is a new flag in 1.7.4 that should speed up classloading.  See the release notes: http://code.google.com/p/googleappengine/wiki/SdkForJavaReleaseNotes.

**Comment by bmuschko** [comment]
Cool, sounds like this flag does something similar to the functionality of the existing `optimizeWar` convention property. This will definitely make it into the next release. Thanks for reporting that.

**Comment by tkruse** [comment]
+1. When is the next release planned for?

**Comment by bmuschko** [comment]
Currently, I am pretty swamped with other work. Would you be interested in working on a pull request for this ticket? Adding this functionality shouldn't be too hard.

**Comment by tkruse** [comment]
Not right now, but possibly in a couple of weeks.

On Thu, Jun 27, 2013 at 11:10 PM, Benjamin Muschko <notifications@github.com

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
