### ISSUE TITLE
Endpoints Support

### ISSUE THREAD

**Issue by devesh** [bmuschko/gradle-gae-plugin#44]
Version 1.7.4 of the appengine SDK includes $APPENGINE_HOME/bin/endpoints.sh for generating API configuration files for the server and client libraries to consume the API. See http://endpoints-trusted-tester.appspot.com/ for details of this upcoming feature.

Add support for generating the API configuration files into the war and for publishing the client libraries.

**Comment by ludoch** [comment]
See https://code.google.com/p/googleappengine/issues/detail?id=8834&sort=-id&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log

We are open to consider participating to this open source project. Would it be fine?

**Comment by bmuschko** [comment]
Absolutely! I'd love more people to contribute to the plugin. There are too many new features with every GAE release . It's almost impossible for me to keep up with adding support for it in the plugin.

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
