### ISSUE TITLE
update backends tasks doesn't reflect java7 settings

### ISSUE THREAD

**Issue by musketyr** [bmuschko/gradle-gae-plugin#45]
`useJava7` convention property is ignored in update backends related tasks. Please, let update backends tasks take advantage of this property too. Currently, if I upload app to frontend it ends up as Java 7 application, but if I upload backend it ends up as Java 6 one.

**Comment by codeconsole** [comment]
This is a blocker for me because what ends up happening is gradle uploads java 7 code and then I get an incompatible version on the upload version because it can't load java 7 bytecode.

**Comment by bmuschko** [comment]
I will try to work on this over the weekend.

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
