### ISSUE TITLE
--host flag does not work

### ISSUE THREAD

**Issue by sheldoan** [bmuschko/gradle-gae-plugin#46]
I'd like to run my appengine project locally via gaeRun on my computer's public facing IP address, but the 'host' flag in appcfg settings does not change the task from running the server on 'localhost'. 

It looks like there is no field for the host in KickstartParams. Is there any way we could get support for this?

Also thanks for this project, otherwise it has been awesome

**Comment by bmuschko** [comment]
Most certainly. Would you mind working on a pull request for it? I am kind of short on time at the moment.
