### ISSUE TITLE
Datastore path ?

### ISSUE THREAD

**Issue by oakstair** [bmuschko/gradle-gae-plugin#47]
I noticed that my local datastore is wiped each time.

I ggogled around and found that I shall pass in

```
--datastore_path=...
```

How is that done with the gae plugin ....

**Comment by bmuschko** [comment]
At the moment this parameter is not supported. Would you mind working on a pull request?

**Comment by bmuschko** [comment]
Please address this issue in the [new repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin) of the plugin.
