### ISSUE TITLE
The TaskContainer.add() method has been deprecated ...

### ISSUE THREAD

**Issue by oakstair** [bmuschko/gradle-gae-plugin#48]
The TaskContainer.add() method has been deprecated and is scheduled to be removed in Gradle 2.0. Please use the create() method instead.

I get the warning above for my gae config which looks like ...

```
gae {
    httpPort = 8888
    jvmFlags = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8889', '-Xmx1024m', '-XX:MaxPermSize=512m']
    optimizeWar = true
    downloadSdk = true

    upload {
        useJava7 = true
    }

    appcfg {
        email = 'xxx@gmail.com'
        passIn = true

        logs {
            severity = 1
            numDays = 1
            outputFile = file('xxx.log')
        }

        app {
            id = 'xxx'
        }
    }
}
```

**Comment by bmuschko** [comment]
The plugin uses a method of the Gradle API that was deprecated with Gradle 1.6. This will require a code change. For now this is just a warning. The plugin will work as expected.

**Comment by oakstair** [comment]
Ok thanks!
