### ISSUE TITLE
systemProp.appengine.sdk.root

### ISSUE THREAD

**Issue by gertcuykens** [bmuschko/gradle-gae-plugin#57]
works
`export APPENGINE_HOME=/home/gert/appengine-java-sdk-1.8.5`

gradle.properties
`systemProp.appengine.sdk.root = '/home/gert/appengine-java-sdk-1.8.5'`

gives me the following error
`Set App Engine SDK root directory does not exist: ''/home/gert/appengine-java-sdk-1.8.5''!`

**Comment by bmuschko** [comment]
A property value in a properties file does not require single quotes. If you remove them you should be good.

**Comment by gertcuykens** [comment]
Thank you :) it works without quotes.
