### ISSUE TITLE
buildConfig

### ISSUE THREAD

**Issue by gertcuykens** [bmuschko/gradle-gae-plugin#58]
Is something like this possible for gae?

```
buildTypes {
    debug {
          buildConfig "public final static String API_ID = $System.env.API_ID;"
          buildConfig "public final static String API_KEY = $System.env.API_KEY;"
    }
}
```

**Comment by bmuschko** [comment]
Build types are not supported but what is it you are trying to achieve?

**Comment by gertcuykens** [comment]
Trying to fetch variables from the environment and generate java code before compiling. The example above is based on this http://stackoverflow.com/questions/17197636/is-it-possible-to-declare-a-variable-in-gradle-usable-in-java

**Comment by bmuschko** [comment]
You can just provide a system property through another task. IMHO providing code through configuration is a bad practice. You should just provide the configuration and then the plugin or task should know what to with it. BTW: You can provide the application ID directly though the exposed DSL for example (see [README file](https://github.com/bmuschko/gradle-gae-plugin/blob/master/README.md)).

**Comment by bmuschko** [comment]
One more addition. This plugin is going to be taken over and maintained by Google. They already set up a new [repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin). Please ask your questions over there. This repository is going to be deprecated.

**Comment by gertcuykens** [comment]
I would like to prevent using hardcoded oauth2 key's in java code.
Anyway I think this would work for me

``` java
task generateSources {
    outputDir = file("$buildDir/generated-src")
    outputs.dir outputDir
    doFirst {
        outputDir.exists() || outputDir.mkdirs()
        new File(outputDir, "Generated.java").write(
            "public final static String API_ID = $System.env.API_ID;\
             public final static String API_KEY = $System.env.API_KEY;"
        )
    }
}
compileJava.source generateSources.outputs.files, sourceSets.main.java
```
