### ISSUE TITLE
Password is visible when typing

### ISSUE THREAD

**Issue by nageshwara** [bmuschko/gradle-gae-plugin#59]
Hi,
First of all thanks for building this gradle plugin. Its been really helpful in our workflow. I would like to report an issue with password input. When we are prompted with password, Its taking it as a standard text without masking it. Making my password visible to my colleagues. Can you please address the issue when you have time.

Thanks.

**Comment by bmuschko** [comment]
As mentioned in the [README file](https://github.com/bmuschko/gradle-gae-plugin/blob/master/README.md), development for this plugin is discontinued in this repository. Please open this issue in the new [repository](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin).
