### ISSUE TITLE
Deploy a given war-file/-content directly to appengine

### ISSUE THREAD

**Issue by vvursT** [bmuschko/gradle-gae-plugin#6]
The gradle-gae-plugin should support deploying a given war-file/exploded-war-directory directly into gae. Therefore the complete build process isn't needed, just the (gaeExplodeWar +) deploy mechanism. I need it to deploy a specific version that already has been released. The syntax could be something like i.e. <gradle gaeUploadWar gae.war>, or maybe you've got a better solution in your mind.

**Comment by bmuschko** [comment]
You should already be able to do this by configuring the existing tasks. Here's an example. Please let me know if that works for you. As a side note I'd recommend you tag every release you make in your VCS so you can easily go back to it and rebuild/upload it.

```
def destDir = file('/Users/vvursT/exploded-war')
gaeExplodeWar.warArchive = file('/Users/vvursT/build/libs/some.war')
gaeExplodeWar.explodedWarDirectory = destDir
gaeUpload.explodedWarDirectory = destDir

task upload(dependsOn: gaeUpload) << {
    description = "Uploading exploded WAR from ${destDir.canonicalPath}"
}
```

**Comment by vvursT** [comment]
Thank you for your fast response. At all this solution works for me, but i got an issue left.
There is no need to do all the work "before" the gaeExplodeWar and gaeUpload. I've got my war-file and just need to explode and upload it. Is there a way to tell break this dependency? Any other suggestions?

**Comment by bmuschko** [comment]
The `gaeExplodeWar` task depends on the `war` task. Therefore, the task rebuilds the WAR whenever you run `gaeExplodeWar`. To make this work you'd probably have to cut that dependency. Try this in the upload task I mentioned above. I am not sure if that will work though:

```
project.tasks.getByName('gaeExplodeWar').dependsOn []
```

**Comment by bmuschko** [comment]
I guess this solved it for you. Therefore, closing the issue. Please reopen it if there's still something to discuss.
