### ISSUE TITLE
Remove usage of WarPluginConvention

### ISSUE THREAD

**Issue by donat** [bmuschko/gradle-gae-plugin#60]
The type will be removed in Gradle 8.0.

https://github.com/bmuschko/gradle-gae-plugin/blob/84db2443b0f52d5fd06e7d4b68d4402a44d64f1a/src/main/groovy/org/gradle/api/plugins/gae/GaePlugin.groovy#L132

**Comment by bmuschko** [comment]
Thanks for the info! This repository is dead. The code base has been taken over by Google. I am going to archive the repo.
